### ISSUE TITLE
[FEATURE REQUEST] Maplibre

### ISSUE THREAD

**Issue by kkdd** [LdDl/horizon#13]
Hello,
I think that the use of [Maplibre](https://maplibre.org/) would be better than MapboxGL, because it is open-source.

**Comment by LdDl** [comment]
Hello!

Thas's exactly what I planned a month ago, but forgot to do =/
I had some plans for Svelte+Maplibre as separate horizon-ui repository actually, but those are my dreams for current time

**Comment by LdDl** [comment]
Happy to announce that I've swapped to Maplibre.
(there is some mapbox-gl-draw under the hood, but I believe it is under v1.x.x Mapbox).

Closing this issue. If you find any bug with Maplibre implementation it is better to open new issue now.
