### ISSUE TITLE
Question: is there a way to find the fastest route between coordinates in the supplied order.

### ISSUE THREAD

**Issue by tamal-appsbee** [LdDl/horizon#2]
Is there  a way to find the fastest route between coordinates in the supplied order:
Example:
Need to find out a shortest path from 'A' to  'B', 'C','X','Y'
The result would be like as per road network.

**Comment by LdDl** [comment]
@tamal-appsbee Hello!
So....
If you provide your coordinates in needed order, e.g.:
```json
{
    "maxStates": 5,
    "stateRadius": 7,
    "gps": [
        {"tm": "2021-04-02T00:00:00", "lonLat": [A-longitude,A-latitude]},
        {"tm": "2021-04-02T00:00:15", "lonLat": [B-longitude, B-latitude]},
        {"tm": "2021-04-02T00:00:30", "lonLat": [C-longitude, C-latitude]},
        {"tm": "2021-04-02T00:00:45","lonLat": [X-longitude, X-latitude]},
        {"tm": "2021-04-02T00:01:00","lonLat": [Y-longitude, Y-latitude]}
    ]
}
```
You will get best route which is choosen by Hidden Markov Model which shortest path "calculator" based on Dijkstra's algorithm.
So it guarantees shortes path in exact order.

**BUT**: *you should know that Hidden Makrov Model picks graph's vertices via some heuristic algorithms, so it doesn't guarantee 100% accurate vertex picking.*

**Comment by tamal-appsbee** [comment]
Thank you @LdDl
