### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by tamal-appsbee** [LdDl/horizon#3]
When trying to install horizon getting following error
Please help me if I am doing something wrong

![image](https://user-images.githubusercontent.com/8500385/113736783-0b094480-971b-11eb-833d-f38d75b8191f.png)

Thanks

**Comment by LdDl** [comment]
Seems like Go-mod is trying to install Fiber of version 2.x.x.

fiber v1:
![image](https://user-images.githubusercontent.com/8864477/113740356-4d298a80-9709-11eb-918a-a7000a974184.png)

fiber v2:
![image](https://user-images.githubusercontent.com/8864477/113740309-41d65f00-9709-11eb-8c28-b9b47b5cea06.png)


@tamal-appsbee,
1. Are you using Go 1.16?
2. Can you disable go modules and try it again?
```shell
export GO111MODULE=off
```

**Comment by tamal-appsbee** [comment]
My go version is : go version go1.14 linux/amd64

**Comment by tamal-appsbee** [comment]
I tried after "export GO111MODULE=off" same issue.

**Comment by LdDl** [comment]
So....
I guess it's better to migrate to Fiber v2 anyway.

We will take care of it

**Comment by tamal-appsbee** [comment]
Thanks @LdDl

**Comment by LdDl** [comment]
@tamal-appsbee 
We've just updated repo to 0.3.6 version.
Now it contains lastest Fiber version (v2.7.1)
Is it good for you now?

**Comment by tamal-appsbee** [comment]
Yes working now
Thank you

**Comment by LdDl** [comment]
Great :)
Closing
